version = 0.1

[mock]
type = "profile"
vector_db.meta = {name="Mock"}
vector_db.engram = {name="Mock"}
llm.retrieve_gen_conversation_direction = {name="Mock"}
llm.retrieve_gen_index = {name="Mock"}
llm.retrieve_prompt_analysis = {name="Mock"}
llm.retrieve_gen_query = {name="Mock"}
db.document = {name="Mock"}
llm.response_main = {name="Mock"}
llm.validate = {name="Mock"}
llm.summary = {name="Mock"}
llm.gen_indices = {name="Mock"}
embedding.gen_embed = {name="Mock"}
llm.sense_initial_summary = {name="Mock"}
llm.sense_scan = {name="Mock"}
llm.sense_full_summary = {name="Mock"}
llm.process = {name="Mock"}

[standard]
type = "pointer"
ptr = "standard-2025-07-01"


[standard-2025-07-01]
type = "profile"
vector_db.meta = {name="ChromaDB",threshold=0.6,n_results=10}
vector_db.engram = {name="ChromaDB",threshold=0.4,n_results=2}
llm.retrieve_gen_conversation_direction = {name="Gemini",model="gemini-2.5-flash"}
llm.retrieve_gen_index = {name="Gemini",model="gemini-2.5-flash"}
llm.retrieve_prompt_analysis = {name="Gemini",model="gemini-2.5-flash"}
llm.retrieve_gen_query = {name="Gemini",model="gemini-2.5-flash"}
db.document = {name="Sqlite"}
llm.response_main = {name="Gemini",model="gemini-2.5-pro",deterministic="true"}
llm.validate = {name="Gemini",model="gemini-2.5-flash",deterministic="true"}
llm.summary = {name="Gemini",model="gemini-2.5-flash"}
llm.gen_indices = {name="Gemini",model="gemini-2.5-pro"}
embedding.gen_embed = {name="Gemini",model="gemini-embedding-001",dimensions=768}
llm.sense_initial_summary = {name="Gemini",model="gemini-2.5-flash"}
llm.sense_scan = {name="Gemini",model="gemini-2.5-flash"}
llm.sense_full_summary = {name="Gemini",model="gemini-2.5-flash"}
llm.process = {name="Gemini",model="gemini-2.5-flash"}


